# Generated by Django 4.2.30 on 2026-08-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
